apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    app: my-app
    deploymentconfig: my-app
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: my-app
        deploymentconfig: my-app
    spec:
      containers:
      - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: 'my-app-db-secret'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: 'my-app-db-secret'
        - name: DB_URL_CONNECTION
          valueFrom:
            secretKeyRef:
              key: database-url
              name: 'my-app-db-secret'
        image: my-app:latest
        imagePullPolicy: Always
        name: my-app
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 9990
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          httpGet:
            path: /health
            port: 9990
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9990
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - my-app
      from:
        kind: ImageStreamTag
        name: my-app:latest
    type: ImageChange
status: {}