# This image provides a base for building and running WildFly applications.
# It builds using maven and runs the resulting artifacts on WildFly 15.0.1 Final

FROM centos/s2i-base-centos7

ADD ./m2-repository $HOME/.m2/repository
